### ISSUE TITLE
Handle inactive Spotify device on auth

### ISSUE THREAD

**Issue by matthieunelmes** [happy-machine/RCD_Api#16]
Needs a better way to handle when there are no active devices available for the user when they first log in.

Possible explore https://developer.spotify.com/documentation/web-api/reference/player/get-a-users-available-devices/

**Comment by renasboy** [comment]
created a PR for that

**Comment by matthieunelmes** [comment]
Potentially fixed with https://github.com/happy-machine/RCD_Api/pull/18
